DEFAULT:
  entity: jzq
  project: mprl-table-tennis
  fields: ["num_global_steps", "eval/is_success", "eval/hit_ball", "eval/reward"]
  output_path: /home/zeqi_jin/Desktop/MasterThesis/code/wandb2numpy/wandb_data/table_tennis/tt_wind

mp3_bb:
  groups: ["mprl-mp3-bb"]
  tags: [["pomdp_2nd"]]
  config:
    sampler.args.env_id:
      values: [ "TableTennisWindProDMP-v0",
                "TableTennisWindReplanProDMP-v0",
                "TableTennisWindReplanProDMPIA-v0" ]

mp3_rp:
  groups: ["mprl-mp3-rp"]
  tags: [["pomdp_2nd"]]
  config:
    sampler.args.env_id:
      values: [ "TableTennisWindProDMP-v0",
                "TableTennisWindReplanProDMP-v0",
                "TableTennisWindReplanProDMPIA-v0" ]

mp3_rp_gpt:
  groups: ["mprl-mp3-rp-gpt"]
  tags: [["pomdp_2nd"]]
  config:
    sampler.args.env_id:
      values: [ "TableTennisWindProDMP-v0",
                "TableTennisWindReplanProDMP-v0",
                "TableTennisWindReplanProDMPIA-v0" ]

mp3_rp_rnn:
  groups: ["mprl-mp3-rp-rnn"]
  tags: [["pomdp_2nd"]]
  config:
    sampler.args.env_id:
      values: [ "TableTennisWindProDMP-v0",
                "TableTennisWindReplanProDMP-v0",
                "TableTennisWindReplanProDMPIA-v0" ]