DEFAULT:
  entity: jzq
  project: mprl-box-pushing-clean
  fields: ["num_global_steps", "eval/reward", "eval/is_success", "eval/episode_energy",
           "eval/box_goal_pos_dist", "eval/box_goal_rot_dist"]
  output_path: /home/zeqi_jin/Desktop/MasterThesis/code/wandb2numpy/wandb_data/box_pushing/bp_mask_entry

mprl-mp3-bb:
  groups: ["mprl-mp3-bb"]
  tags: [["pomdp_1st"]]
  config:
    sampler.args.env_id:
      values: [ "BoxPushingTSMaskEntryProMP-v0",
                "BoxPushingTSMaskEntryReplanProDMP-v0",
                "BoxPushingTSMaskEntryReplanProDMPIA-v0" ]

mprl-mp3-rp:
  groups: ["mprl-mp3-rp"]
  tags: [["pomdp_1st"]]
  config:
    sampler.args.env_id:
      values: [ "BoxPushingTSMaskEntryProMP-v0",
                "BoxPushingTSMaskEntryReplanProDMP-v0",
                "BoxPushingTSMaskEntryReplanProDMPIA-v0" ]

mprl-mp3-rp-gpt:
  groups: ["mprl-mp3-rp-gpt"]
  tags: [["pomdp_1st"]]
  config:
    sampler.args.env_id:
      values: [ "BoxPushingTSMaskEntryProMP-v0",
                "BoxPushingTSMaskEntryReplanProDMP-v0",
                "BoxPushingTSMaskEntryReplanProDMPIA-v0" ]

mprl-mp3-rp-rnn:
  groups: ["mprl-mp3-rp-rnn"]
  tags: [["pomdp_1st"]]
  config:
    sampler.args.env_id:
      values: [ "BoxPushingTSMaskEntryProMP-v0",
                "BoxPushingTSMaskEntryReplanProDMP-v0",
                "BoxPushingTSMaskEntryReplanProDMPIA-v0" ]