DEFAULT:
  entity: jzq
  project: mprl-box-pushing-clean
  fields: ["num_global_steps", "eval/reward", "eval/is_success", "eval/episode_energy",
           "eval/box_goal_pos_dist", "eval/box_goal_rot_dist"]
  output_path: /home/zeqi_jin/Desktop/thesis/code/wandb2numpy/wandb_data/box_pushing/bp_mask_vel

mp3_bb:
  groups: ["mprl-mp3-bb"]
  tags: [["pomdp_1st"]]
  config:
    sampler.args.env_id:
      values: [ "BoxPushingTSMaskVelProMP-v0",
                "BoxPushingTSMaskVelReplanProDMP-v0",
                "BoxPushingTSMaskVelReplanProDMPIA-v0" ]

mp3_rp:
  groups: ["mprl-mp3-rp"]
  tags: [["pomdp_1st"]]
  config:
    sampler.args.env_id:
      values: [ "BoxPushingTSMaskVelProMP-v0",
                "BoxPushingTSMaskVelReplanProDMP-v0",
                "BoxPushingTSMaskVelReplanProDMPIA-v0" ]

mp3_rp_gpt:
  groups: ["mprl-mp3-rp-gpt"]
  tags: [["pomdp_1st"]]
  config:
    sampler.args.env_id:
      values: [ "BoxPushingTSMaskVelProMP-v0",
                "BoxPushingTSMaskVelReplanProDMP-v0",
                "BoxPushingTSMaskVelReplanProDMPIA-v0" ]

mp3_rp_rnn:
  groups: ["mprl-mp3-rp-rnn"]
  tags: [["pomdp_1st"]]
  config:
    sampler.args.env_id:
      values: [ "BoxPushingTSMaskVelProMP-v0",
                "BoxPushingTSMaskVelReplanProDMP-v0",
                "BoxPushingTSMaskVelReplanProDMPIA-v0" ]